/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrincipalLoginRouteImport } from './routes/principal.login'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as SuperLoginRouteImport } from './routes/super.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalLoginRoute = PrincipalLoginRouteImport.update({
  id: '/principal/login',
  path: '/principal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/super/',
  path: '/super/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/super/login',
  path: '/super/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/principal/login': typeof PrincipalLoginRoute
  '/super/login': typeof SuperLoginRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/principal/login': typeof PrincipalLoginRoute
  '/super/login': typeof SuperLoginRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/principal/login': typeof PrincipalLoginRoute
  '/super/login': typeof SuperLoginRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/principal/login' | '/super/login' | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/principal/login' | '/super/login' | '/super'
  id: '__root__' | '/' | '/principal/login' | '/super/login' | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrincipalLoginRoute: typeof PrincipalLoginRoute
  SuperLoginRoute: typeof SuperLoginRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal/login': {
      id: '/principal/login'
      path: '/principal/login'
      fullPath: '/principal/login'
      preLoaderRoute: typeof PrincipalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/super'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/login': {
      id: '/super/login'
      path: '/super/login'
      fullPath: '/super/login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrincipalLoginRoute: PrincipalLoginRoute,
  SuperLoginRoute: SuperLoginRoute,
  SuperIndexRoute: SuperIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
